version: '3'
services:
  my-app-prod:
    container_name: my-app-prod
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - '80:80'
      - '443:443'
    environment:
      CERTBOT_EMAIL: veronica@blazhko.tech
    volumes:
      - ./nginx:/etc/nginx/user.conf.d:Z
      - letsencrypt:/etc/letsencrypt:Z
volumes:
  letsencrypt: